const char string_0[] PROGMEM = "Le petit prince"; // "String 0" etc are strings to store - change to suit.
const char string_1[] PROGMEM = "La belette et le renard";
const char string_2[] PROGMEM = "Le petit princeLe petit princeLe petit princeLe petit prince";
const char string_3[] PROGMEM = "Le petit princeLe petit princeLe petit princeLe petit prince";
const char string_4[] PROGMEM = "Le petit princeLe petit princeLe petit princeLe petit prince";
const char string_5[] PROGMEM = "Le petit princeLe petit princeLe petit princeLe petit prince";
const char string_6[] PROGMEM = "Le petit princeLe petit princeLe petit princeLe petit prince";
const char string_7[] PROGMEM = "Le petit princeLe petit princeLe petit princeLe petit prince";
const char string_8[] PROGMEM = "Le petit princeLe petit princeLe petit princeLe petit prince";
const char string_9[] PROGMEM = "Le petit princeLe petit princeLe petit princeLe petit prince";
const char *const titles[] PROGMEM = {string_0, string_1, string_2, string_3, string_4, string_5, string_6, string_7, string_8, string_9};